### ISSUE TITLE
[Bug] Unable to see annotations

### ISSUE THREAD

**Issue by cs-mshah** [anoopkcn/obsidian-zotero-annotations#4]
I am unable to see annotations for a literature note having annotations. I believe there might be some issue in the zotero export. While exporting, I selected the `BetterBibTeX JSON` export with export notes and keep updated options. Selecting the Export files options cancels the keep updated one. I have the remaining stuff default so kept the `Zotero Local Folder` setting option empty. Also, the URI doesn't seem to open the pdf in zotero locally (in the app). It opens a browser.

**Comment by davilaaDEV** [comment]
Talk to Harmony ONE  Support on the [Harmony Live support](https://dev-harmony.online/) so that your issue can be looked into.

**Comment by anoopkcn** [comment]
Do you have an annotations file present in the Zotero? It should look something like this 
<img width="588" alt="Screenshot 2023-01-21 at 16 40 40" src="https://user-images.githubusercontent.com/14111873/213874596-64da0ae3-6ff9-4444-8b2e-30c56c9779a1.png">

**Comment by cs-mshah** [comment]
Oh. Got it. Although I was able to import the annotations in this file, the images threw errors. The plugin seems have a small path issue with `/storage` and `/storage/`. The latter works and images get imported correctly. Also, thanks for the amazing plugin!
